# Generated by Django 5.0.7 on 2024-12-01 18:44

import common.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name', models.CharField(max_length=100, unique=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Район/Город',
                'verbose_name_plural': 'Районы/Города',
                'db_table': 's_district',
                'ordering': ['pk'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=70, verbose_name='ФИО')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Телефон')),
                ('is_active', models.BooleanField(db_column='is_activity', default=True, verbose_name='Активность')),
                ('e_mail', models.EmailField(blank=True, max_length=70, null=True, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'db_table': 's_employee',
                'ordering': ['-pk'],
                'managed': False,
            },
            bases=(common.mixins.InvalidateCachedPropertiesMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('phone_number1', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона #1')),
                ('phone_number2', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона #2')),
                ('e_mail', models.EmailField(blank=True, max_length=70, null=True, verbose_name='Email')),
                ('address_actual', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес фактический')),
                ('address_legal', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес юридический')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
                'db_table': 's_office',
                'ordering': ['-pk'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OfficeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=30, unique=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Тип организации',
                'verbose_name_plural': 'Тип организаций',
                'db_table': 's_office_type',
                'ordering': ['pk'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=70, unique=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Роли',
                'db_table': 's_role',
                'ordering': ['pk'],
                'managed': False,
            },
        ),
    ]
