# Generated by Django 5.0.7 on 2024-12-01 20:44

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_code', models.CharField(max_length=30, verbose_name='Шифр')),
                ('material_name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('cost_value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Себестоимость материала')),
                ('labor_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Трудозатраты, часы')),
                ('cost_work', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Себестоимость трудозатрат')),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Материалы',
                'db_table': 's_material',
                'ordering': ['-pk'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TaskMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_count', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Количество')),
                ('material_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Стоимость материала')),
                ('labor_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Трудозатраты')),
                ('work_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Стоимость работ')),
                ('material_count_fact', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Фактически сделано')),
                ('material_cost_total', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Стоимость работ итого')),
                ('work_cost_total', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Стоимость трудозатрат итого')),
            ],
            options={
                'verbose_name': 'Материал к работе',
                'verbose_name_plural': 'Материалы к работам',
                'db_table': 'd_task_material',
                'ordering': ['-pk'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UnitMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=100, unique=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Единица измерения',
                'verbose_name_plural': 'Единицы измерений',
                'db_table': 's_unit_measure',
                'ordering': ['pk'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_code', models.CharField(max_length=30, verbose_name='Шифр')),
                ('work_name', models.CharField(max_length=255, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Работа',
                'verbose_name_plural': 'Работы',
                'db_table': 's_work',
                'ordering': ['-pk'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('date_start', models.DateField(blank=True, null=True, verbose_name='Дата')),
                ('date_stop', models.DateField(blank=True, null=True, verbose_name='Плановя дата')),
                ('date_fact', models.DateField(blank=True, null=True, verbose_name='Фактическая дата')),
                ('date_add', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время добавления')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='directory.task', verbose_name='Родительская запись')),
                ('s_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='directory.employee', verbose_name='Ответственный')),
                ('s_work', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='directory.work', verbose_name='Работа')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'db_table': 'd_task',
                'ordering': ['-pk'],
                'managed': True,
            },
        ),
    ]
